spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
#  jackson:
#    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
#    password: 123456
    password: Wj123456!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /sell



#logging:
#  pattern:
#    console: "%d - %5p ----- %msg%n"
#  file:
#    #    path: C:\Users\MyJinji\Desktop
#    name: C:\Users\MyJinji\Desktop\sell.log
#  level:
#    root: info
#    com.wj.sell.LoggerTest: debug
